server:
  port: 8085

spring:
  application:
    name: textSaver

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5466}/${DB_NAME:word_db}
    username: ${USER_NAME:user}
    password: ${PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: khan.generator.textsaver.dto.WordPayload
